package server;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Observable;
import java.util.Observer;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.text.DefaultCaret;

import jobs.JobSchedulingEvent;

public class ServerView extends javax.swing.JFrame implements Observer {
	private static final long serialVersionUID = -5346255320116138428L;
	Server server;

    public ServerView(Server server) {
    	setResizable(false);
        this.server = server;
        server.addObserver(this);
        initComponents();
        this.setSize(new Dimension(1150,490));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

    	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		contentPane = new JPanel();
		contentPane.setBorder(null);
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JPanel panel_2 = new JPanel();
		panel_2.setBounds(678, 5, 458, 452);
		contentPane.add(panel_2);
		
		lblClients = new JLabel("Clients:");
		lblClients.setFont(new Font("Tahoma", Font.BOLD, 11));
		
		JScrollPane scrollPane_1 = new JScrollPane();
		GroupLayout gl_panel_2 = new GroupLayout(panel_2);
		gl_panel_2.setHorizontalGroup(
			gl_panel_2.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel_2.createSequentialGroup()
					.addContainerGap()
					.addGroup(gl_panel_2.createParallelGroup(Alignment.LEADING)
						.addComponent(lblClients, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE)
						.addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE, 438, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		gl_panel_2.setVerticalGroup(
			gl_panel_2.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel_2.createSequentialGroup()
					.addComponent(lblClients)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE, 421, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		
		clientsField = new JTextPane();
		DefaultCaret caret = (DefaultCaret) clientsField.getCaret();
		caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
		
		scrollPane_1.setViewportView(clientsField);
		panel_2.setLayout(gl_panel_2);
		
		JPanel panel = new JPanel();
		panel.setBounds(5, 5, 215, 439);
		contentPane.add(panel);
		
		JButton btnDisconnectFromServer = new JButton("Request CPU load");
		btnDisconnectFromServer.setBounds(0, 140, 215, 23);
		btnDisconnectFromServer.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				server.requestReport();
			}
		});
		panel.setLayout(null);
		panel.add(btnDisconnectFromServer);
		
		lblPort = new JLabel("Port: ");
		lblPort.setBounds(10, 11, 195, 32);
		panel.add(lblPort);
		lblPort.setFont(new Font("Tahoma", Font.BOLD, 11));
		
		lblAddress = new JLabel("Address:");
		lblAddress.setBounds(10, 46, 195, 32);
		panel.add(lblAddress);
		lblAddress.setFont(new Font("Tahoma", Font.BOLD, 11));
		
		JButton btnNewJob = new JButton("New job");
		btnNewJob.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				String command = JOptionPane.showInputDialog(panel, "Enter the command", null);
				int priority = Integer.parseInt(JOptionPane.showInputDialog(panel, "Enter the priority of the job", null));
				int deadline = Integer.parseInt(JOptionPane.showInputDialog(panel, "Enter the deadline as an integer", null));
				server.getDatabase().addJob(command, priority, deadline);
			}
		});
		btnNewJob.setBounds(0, 174, 215, 23);
		panel.add(btnNewJob);
		
		JButton btnGetJobStatus = new JButton("Get job status");
		btnGetJobStatus.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int jobId = Integer.parseInt(JOptionPane.showInputDialog(panel, "Enter the job id", null));
				int status = server.getDatabase().getJobStatus(jobId);
				server.log("The database returned the following status: " + JobSchedulingEvent.getStatus(status));
			}
		});
		btnGetJobStatus.setBounds(0, 208, 215, 23);
		panel.add(btnGetJobStatus);
		
		JButton btnSetJobStatus = new JButton("Set job status");
		btnSetJobStatus.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int jobId = Integer.parseInt(JOptionPane.showInputDialog(panel, "Enter the job id", null));
				int status = Integer.parseInt(JOptionPane.showInputDialog(panel, "Enter the new job status", null));
				server.getDatabase().setJobStatus(jobId, status);
			}
		});
		btnSetJobStatus.setBounds(0, 242, 215, 23);
		panel.add(btnSetJobStatus);
		
		JPanel panel_1 = new JPanel();
		panel_1.setBounds(221, 5, 458, 452);
		contentPane.add(panel_1);
		
		JLabel lblLogger = new JLabel("Logger:");
		lblLogger.setFont(new Font("Tahoma", Font.BOLD, 11));
		
		JScrollPane scrollPane = new JScrollPane();
		GroupLayout gl_panel_1 = new GroupLayout(panel_1);
		gl_panel_1.setHorizontalGroup(
			gl_panel_1.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel_1.createSequentialGroup()
					.addComponent(lblLogger, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE)
					.addGap(38))
				.addGroup(gl_panel_1.createSequentialGroup()
					.addGap(10)
					.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
					.addContainerGap())
		);
		gl_panel_1.setVerticalGroup(
			gl_panel_1.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel_1.createSequentialGroup()
					.addComponent(lblLogger)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
					.addContainerGap())
		);
		
		messageField = new JTextPane();
		DefaultCaret caret2 = (DefaultCaret) messageField.getCaret();
		caret2.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
		
		scrollPane.setViewportView(messageField);
		panel_1.setLayout(gl_panel_1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel contentPane;
	private JLabel lblAddress;
	private JLabel lblPort;
	private JLabel lblClients;
	private JTextPane messageField;
	private JTextPane clientsField;
    // End of variables declaration//GEN-END:variables


    public void update(Observable ob, Object o) {
    	lblAddress.setText("Adress: " + server.getAddress());
        lblPort.setText("port: " + server.getAddress().getPort());
        lblClients.setText("Clients(" + server.getClients().size() + "):");

        setTitle(server.getAddress().toString());

        messageField.setText(server.getLoggerText());
        clientsField.setText(server.getClientsText());
    }
}
