# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=256)),
                ('priority', models.IntegerField(default=1)),
                ('deadline', models.DateTimeField(verbose_name='Requested deadline')),
                ('idOnServer', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='JobSchedulingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateTimeField(verbose_name='Date of event')),
                ('schedStatus', models.IntegerField(choices=[(0, 'entered'), (1, 'scheduled'), (2, 'running'), (3, 'finished'), (4, 'failed'), (5, 'cancelled'), (6, 'killed')])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_web.Job')),
            ],
        ),
        migrations.CreateModel(
            name='LoadMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Measurement date/time')),
                ('cpuLoad', models.FloatField()),
                ('memoryLoad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('hostport', models.IntegerField(default=8901)),
                ('address', models.CharField(max_length=32)),
                ('displayName', models.CharField(max_length=32)),
                ('cpuName', models.CharField(max_length=32)),
                ('cpuCores', models.IntegerField(blank=True, default=1)),
                ('memoryAmount', models.FloatField()),
                ('idOnServer', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=32)),
                ('superGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler_web.ServerGroup')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='serverGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler_web.ServerGroup'),
        ),
        migrations.AddField(
            model_name='loadmeasurement',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_web.Server'),
        ),
        migrations.AddField(
            model_name='jobschedulingevent',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler_web.Server'),
        ),
    ]
