# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=256)),
                ('priority', models.IntegerField(default=1)),
                ('deadline', models.DateTimeField(verbose_name='Requested deadline')),
                ('enteredDate', models.DateTimeField(verbose_name='Date of entry')),
                ('scheduledDate', models.DateTimeField(null=True, verbose_name='Scheduled start date')),
                ('startedDate', models.DateTimeField(null=True, verbose_name='Start date')),
                ('finishedDate', models.DateTimeField(null=True, verbose_name='End date')),
                ('schedStatus', models.IntegerField(choices=[(0, 'entered'), (1, 'scheduled'), (2, 'running'), (3, 'finished'), (4, 'failed'), (5, 'cancelled'), (6, 'killed')])),
            ],
        ),
        migrations.CreateModel(
            name='LoadMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Measurement date/time')),
                ('cpuLoad', jsonfield.fields.JSONField(default=dict)),
                ('memoryLoad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('cpuName', models.CharField(max_length=32)),
                ('memoryAmount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='serverGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler_web.ServerGroup'),
        ),
        migrations.AddField(
            model_name='loadmeasurement',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_web.Server'),
        ),
    ]
