# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servergroup',
            name='superGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler_web.ServerGroup'),
        ),
        migrations.AlterField(
            model_name='server',
            name='serverGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler_web.ServerGroup'),
        ),
    ]
