# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_web', '0002_auto_20170308_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finishedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduledDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled start date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='startedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
