# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_web', '0003_auto_20170316_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSchedulingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateTimeField(verbose_name='Date of event')),
                ('schedStatus', models.IntegerField(choices=[(0, 'entered'), (1, 'scheduled'), (2, 'running'), (3, 'finished'), (4, 'failed'), (5, 'cancelled'), (6, 'killed')])),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='enteredDate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='finishedDate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='schedStatus',
        ),
        migrations.RemoveField(
            model_name='job',
            name='scheduledDate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='startedDate',
        ),
        migrations.AddField(
            model_name='jobschedulingevent',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_web.Job'),
        ),
    ]
