# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_web', '0004_auto_20170316_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpuCores',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='loadmeasurement',
            name='cpuLoad',
            field=models.FloatField(),
        ),
    ]
